### ISSUE TITLE
New lines in docs generated from param tag won't render as markdown tables

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-dodoc#20]
This generated docs:

![image](https://user-images.githubusercontent.com/38409137/147888281-c3a9ee83-9fd8-48de-a0b3-bd556f7365ce.png)

Result:
![image](https://user-images.githubusercontent.com/38409137/147888287-d7567cca-feec-4a0e-adbf-b6521f583720.png)

Fix:
![image](https://user-images.githubusercontent.com/38409137/147888296-60589036-eda0-4e4a-971f-d23bcb284da7.png)

Fix result:
![image](https://user-images.githubusercontent.com/38409137/147888300-1ea07258-36a0-4f67-9439-80f625d2655f.png)

**Comment by clemlak** [comment]
Issue solved thanks to @jonahsnider 👌
