### ISSUE TITLE
Contract/Interface with the same name as another in a different file or directory gets clobbered

### ISSUE THREAD

**Issue by andy-uphold** [primitivefinance/primitive-dodoc#28]
The way this is written right now, the docs are written into a single, flat, directory.

This means that any second Contract or Interface with the same name as another - although with a different qualified name, eg in a different file or dir - will overwrite the doc output of the first one.

I suggest that you have a config option to preserve the directory/filename structure of the contracts.

As this repo is closed, I have coded up a suggested way to do this here, on a Pull Request on my fork of your repo:

https://github.com/primitivefinance/primitive-dodoc/pull/27

**Comment by clemlak** [comment]
Thank you for opening this issue and making your PR! However this feature was already added by another PR (https://github.com/primitivefinance/primitive-dodoc/pull/23) and should be available in the next Dodoc release!

**Comment by andy-uphold** [comment]
Great news! Thanks. When is that likely to be? The last release was November 08, 2021... :(

**Comment by clemlak** [comment]
Most likely next week I guess, in the meantime you can download the `develop` version that contains these new features `yarn add @primitivefi/hardhat-dodoc@develop`.

**Comment by andy-uphold** [comment]
That works perfectly, and gives beautifully formatted output. Thank you. I even found that you now support globbing on the include and exclude options - greatly appreciated! :)

The only thing missing now is an index.md to show the structure in each directory. Do you have plans to add that too or would you mind if I did?

**Comment by clemlak** [comment]
That's an interesting idea! Not sure if we are going to build it anytime soon so feel free to open a PR :)
