### ISSUE TITLE
Parameter `runOnCompile` ignored

### ISSUE THREAD

**Issue by grcasanova** [primitivefinance/primitive-dodoc#9]
First of all thanks for the useful package.
I'd like to point out that the parameter `runOnCompile` set to _false_ does not make any difference and docs are generated as usual when running `yarn compile`.

**Comment by ylv-io** [comment]
Yes. This is an issue.

**Comment by clemlak** [comment]
Thanks for pointing that out, I'll work on a fix!

**Comment by clemlak** [comment]
It's fixed in the latest release!
